### ISSUE TITLE
Error with gnutls_record_send() and GNUTLS_E_AGAIN

### ISSUE THREAD

**Issue by Karlson2k** [abligh/tlsproxy#1]
Instead of using `len` to mark part of the buffer as "sent" you are using negative value of `ret` at https://github.com/abligh/tlsproxy/blob/master/crypto-gnutls.c#L607.
Code can be simplified:

``` C
          do
            {
              ret = gnutls_record_send (s->session, addr, len);
            }
          while (ret == GNUTLS_E_INTERRUPTED && !quit (s));
          if (quit (s))
            break;
          if (ret < 0)
            {
              if (ret != GNUTLS_E_AGAIN)
                {
                  errout (s, "Error on write to crypto socket: %s\n",
                      gnutls_strerror (ret));
                  goto error;
                }
            }
          else
            bufDoneRead (plainToCrypt, ret);  /* mark ret bytes as read from the buffer */
```

**Comment by abligh** [comment]
I don't understand the issue.

`bufDoneRead` is within the `else` block of `if (ret < 0)`, so can only ever execute if `ret >= 0`, so there is no danger of using a negative value.

If I used `len` instead of `ret`, then I'd be assuming `gnutls_record_send` was guaranteed to send all the bytes required. The documentation for this function explicitly says that _'The number of bytes sent might be less than `sizeofdata`'_. That means to mark `len` bytes as sent would be wrong, as the function can succeed whilst sending less than `len` bytes.

**Comment by abligh** [comment]
Actually the para re the `else` that I wrote is wrong - I was looking at your code!

The next para is right though. As `if (ret < 0)` has an embedded `goto`, the problem only exists I think if `GNUTLS_E_AGAIN` is returned. I think your simplified code is also wrong because it does not set `tls_wr_interrupted` on `GNU_TLS_E_AGAIN`.

I believe the simplest fix is to insert `if (ret >0)` above `bufDoneRead (...)`. Do you agree?

**Comment by Karlson2k** [comment]
My code has two fixes:
- Value of 'GNU_TLS_E_AGAIN' is not used to update buffer positions.
- Simplification: GnuTLS actually doesn't **require** you to use `NULL` in case of `GNU_TLS_E_AGAIN`. You **may** use it if it's convenient, but if you know that data is not changed before next call of `gnutls_record_send()`, you may use the same data instead. Looking on GnuTLS sources you may find that next invocation of `gnutls_record_send()` (after fail) will result only in sending already buffered (and encrypted) data.

**Comment by abligh** [comment]
Sorry for the delay.

Commit https://github.com/abligh/tlsproxy/commit/60f0aa01f53faaab73f762b63c4e9d4d568f6931 should fix the main issue, i.e. calling `bufDoneRead` with a negative length in the case of `GNU_TLS_E_AGAIN`.

I understand what you are trying to do within the simplification, but I don't think it's necessarily right (and if it is, it's not complete). You will see that on `GNU_TLS_E_AGAIN` this sets `tls_wr_interrupted`. That's examined in setting the parameters to `gnu_tls_record_send` and I'll take your word for it you can call it with normal parameters as opposed to using `NULL`. You are no longer setting this, which means that the other places that check this flag won't pick it up, e.g.:

```
      if (bufIsEmpty (plainToCrypt) && !tls_wr_interrupted)
        {
          cryptEOF = TRUE;
          break;
        }
```

and

```
      if (!bufIsEmpty (plainToCrypt) || tls_wr_interrupted)
        FD_SET (cryptfd, &writefds);
```

Now, I think your logic is that if `tls_wr_interrupted` is set, then `bufIsEmpty(plainToCrypt)` must have been false in the first place (i.e. there must have been data in that buffer), and nothing can have made it true since as nothing else within that loop empties that buffer. I believe that is probably correct, but would need to check further. But in any case, if that's right, then _all_ references to `tls_wr_interrupted` should be removed, else the code is looking at a variable that is never set.

For that reason, I'd like to keep the simplification item separate from the bug fix. I'm thus going to close this issue. Feel free to reopen a change with the simplification in alone that entirely removes `tls_wr_interrupted`.
